<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="4" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-25T09:53:32 ICT" name="UI Automation Suite" finished-at="2025-07-25T09:53:48 ICT" duration-ms="15857">
    <groups>
    </groups>
    <test started-at="2025-07-25T09:53:32 ICT" name="Login Test" finished-at="2025-07-25T09:53:48 ICT" duration-ms="15857">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:32 ICT" name="setup" finished-at="2025-07-25T09:53:44 ICT" duration-ms="11732" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="setUpTest()[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:44 ICT" name="setUpTest" finished-at="2025-07-25T09:53:44 ICT" duration-ms="371" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method is-config="true" signature="setUpTest()[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:44 ICT" name="setUpTest" finished-at="2025-07-25T09:53:44 ICT" duration-ms="683" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method signature="testAccountInputMaxLength()[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:44 ICT" name="testAccountInputMaxLength" description="TC02 - Account input max length 10" finished-at="2025-07-25T09:53:45 ICT" duration-ms="452" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAccountInputMaxLength -->
        <test-method signature="testInvalidCredentials()[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:44 ICT" name="testInvalidCredentials" description="TC08 - Invalid credentials" finished-at="2025-07-25T09:53:45 ICT" duration-ms="900" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Account not found or password incorrect.] but found [Account]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Account not found or password incorrect.] but found [Account]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at tests.LoginTest.testInvalidCredentials(LoginTest.java:82)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidCredentials -->
        <test-method is-config="true" signature="captureScreenshot(org.testng.ITestResult)[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:45 ICT" name="captureScreenshot" finished-at="2025-07-25T09:53:45 ICT" duration-ms="126" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testAccountInputMaxLength status=SUCCESS method=LoginTest.testAccountInputMaxLength()[pri:0, instance:tests.LoginTest@4201a617] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureScreenshot -->
        <test-method is-config="true" signature="setUpTest()[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:45 ICT" name="setUpTest" finished-at="2025-07-25T09:53:45 ICT" duration-ms="339" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method signature="testPasswordInputMaxLength()[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:45 ICT" name="testPasswordInputMaxLength" description="TC03 - Password input max length 10" finished-at="2025-07-25T09:53:45 ICT" duration-ms="130" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPasswordInputMaxLength -->
        <test-method is-config="true" signature="captureScreenshot(org.testng.ITestResult)[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:45 ICT" name="captureScreenshot" finished-at="2025-07-25T09:53:45 ICT" duration-ms="95" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testPasswordInputMaxLength status=SUCCESS method=LoginTest.testPasswordInputMaxLength()[pri:0, instance:tests.LoginTest@4201a617] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureScreenshot -->
        <test-method is-config="true" signature="setUpTest()[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:45 ICT" name="setUpTest" finished-at="2025-07-25T09:53:46 ICT" duration-ms="295" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method is-config="true" signature="captureScreenshot(org.testng.ITestResult)[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:45 ICT" name="captureScreenshot" finished-at="2025-07-25T09:53:46 ICT" duration-ms="385" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testInvalidCredentials status=FAILURE method=LoginTest.testInvalidCredentials()[pri:0, instance:tests.LoginTest@4201a617] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureScreenshot -->
        <test-method signature="testScreenInitializesCorrectly()[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:46 ICT" name="testScreenInitializesCorrectly" description="TC01 - Screen initializes correctly" finished-at="2025-07-25T09:53:46 ICT" duration-ms="391" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login form should be displayed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login form should be displayed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at tests.LoginTest.testScreenInitializesCorrectly(LoginTest.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testScreenInitializesCorrectly -->
        <test-method is-config="true" signature="setUpTest()[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:46 ICT" name="setUpTest" finished-at="2025-07-25T09:53:46 ICT" duration-ms="281" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method signature="testSuccessfulLoginAsAdmin()[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:46 ICT" name="testSuccessfulLoginAsAdmin" description="TC06 - Successful login as Admin" finished-at="2025-07-25T09:53:46 ICT" duration-ms="442" status="FAIL">
          <exception class="org.openqa.selenium.StaleElementReferenceException">
            <message>
              <![CDATA[stale element reference: stale element not found
  (Session info: chrome=138.0.7204.169)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.2.1', java.version: '17.0.7'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [95cbec6602d2f88172597fd5473a5a81, sendKeysToElement {id=f.CF55D5EDF931C8D18C7445053BEB5C9D.d.509F7595ABF817B114BE5D742E6CF008.e.43, value=[Ljava.lang.CharSequence;@50a86787}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 138.0.7204.169, chrome: {chromedriverVersion: 138.0.7204.168 (3e8d82e86e9..., userDataDir: /var/folders/kp/fmlbc39d23q...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:61638}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: mac, proxy: Proxy(), se:cdp: ws://localhost:61638/devtoo..., se:cdpVersion: 138.0.7204.169, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on mac (95cbec6602d2f88172597fd5473a5a81)] -> id: account]
Session ID: 95cbec6602d2f88172597fd5473a5a81]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.StaleElementReferenceException: stale element reference: stale element not found
  (Session info: chrome=138.0.7204.169)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.2.1', java.version: '17.0.7'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [95cbec6602d2f88172597fd5473a5a81, sendKeysToElement {id=f.CF55D5EDF931C8D18C7445053BEB5C9D.d.509F7595ABF817B114BE5D742E6CF008.e.43, value=[Ljava.lang.CharSequence;@50a86787}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 138.0.7204.169, chrome: {chromedriverVersion: 138.0.7204.168 (3e8d82e86e9..., userDataDir: /var/folders/kp/fmlbc39d23q...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:61638}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: mac, proxy: Proxy(), se:cdp: ws://localhost:61638/devtoo..., se:cdpVersion: 138.0.7204.169, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on mac (95cbec6602d2f88172597fd5473a5a81)] -> id: account]
Session ID: 95cbec6602d2f88172597fd5473a5a81
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:110)
at pages.BasePage.type(BasePage.java:32)
at pages.LoginPage.enterAccount(LoginPage.java:20)
at tests.LoginTest.testSuccessfulLoginAsAdmin(LoginTest.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.StaleElementReferenceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSuccessfulLoginAsAdmin -->
        <test-method is-config="true" signature="captureScreenshot(org.testng.ITestResult)[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:46 ICT" name="captureScreenshot" finished-at="2025-07-25T09:53:46 ICT" duration-ms="124" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testScreenInitializesCorrectly status=FAILURE method=LoginTest.testScreenInitializesCorrectly()[pri:0, instance:tests.LoginTest@4201a617] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureScreenshot -->
        <test-method is-config="true" signature="setUpTest()[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:46 ICT" name="setUpTest" finished-at="2025-07-25T09:53:46 ICT" duration-ms="303" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method signature="testSuccessfulLoginAsStaff()[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:46 ICT" name="testSuccessfulLoginAsStaff" description="TC07 - Successful login as Staff" finished-at="2025-07-25T09:53:47 ICT" duration-ms="409" status="FAIL">
          <exception class="org.openqa.selenium.StaleElementReferenceException">
            <message>
              <![CDATA[stale element reference: stale element not found
  (Session info: chrome=138.0.7204.169)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.2.1', java.version: '17.0.7'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [95cbec6602d2f88172597fd5473a5a81, sendKeysToElement {id=f.CF55D5EDF931C8D18C7445053BEB5C9D.d.5B30AD9338D7DC8A5B9959A646810C6E.e.52, value=[Ljava.lang.CharSequence;@52a87c52}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 138.0.7204.169, chrome: {chromedriverVersion: 138.0.7204.168 (3e8d82e86e9..., userDataDir: /var/folders/kp/fmlbc39d23q...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:61638}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: mac, proxy: Proxy(), se:cdp: ws://localhost:61638/devtoo..., se:cdpVersion: 138.0.7204.169, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on mac (95cbec6602d2f88172597fd5473a5a81)] -> id: account]
Session ID: 95cbec6602d2f88172597fd5473a5a81]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.StaleElementReferenceException: stale element reference: stale element not found
  (Session info: chrome=138.0.7204.169)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.2.1', java.version: '17.0.7'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [95cbec6602d2f88172597fd5473a5a81, sendKeysToElement {id=f.CF55D5EDF931C8D18C7445053BEB5C9D.d.5B30AD9338D7DC8A5B9959A646810C6E.e.52, value=[Ljava.lang.CharSequence;@52a87c52}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 138.0.7204.169, chrome: {chromedriverVersion: 138.0.7204.168 (3e8d82e86e9..., userDataDir: /var/folders/kp/fmlbc39d23q...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:61638}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: mac, proxy: Proxy(), se:cdp: ws://localhost:61638/devtoo..., se:cdpVersion: 138.0.7204.169, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on mac (95cbec6602d2f88172597fd5473a5a81)] -> id: account]
Session ID: 95cbec6602d2f88172597fd5473a5a81
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:110)
at pages.BasePage.type(BasePage.java:32)
at pages.LoginPage.enterAccount(LoginPage.java:20)
at tests.LoginTest.testSuccessfulLoginAsStaff(LoginTest.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.StaleElementReferenceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSuccessfulLoginAsStaff -->
        <test-method is-config="true" signature="captureScreenshot(org.testng.ITestResult)[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:46 ICT" name="captureScreenshot" finished-at="2025-07-25T09:53:46 ICT" duration-ms="105" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testSuccessfulLoginAsAdmin status=FAILURE method=LoginTest.testSuccessfulLoginAsAdmin()[pri:0, instance:tests.LoginTest@4201a617] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureScreenshot -->
        <test-method is-config="true" signature="setUpTest()[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:46 ICT" name="setUpTest" finished-at="2025-07-25T09:53:47 ICT" duration-ms="288" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method signature="testValidationMissingAccount()[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:47 ICT" name="testValidationMissingAccount" description="TC04 - Validation missing Account" finished-at="2025-07-25T09:53:47 ICT" duration-ms="651" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidationMissingAccount -->
        <test-method is-config="true" signature="captureScreenshot(org.testng.ITestResult)[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:47 ICT" name="captureScreenshot" finished-at="2025-07-25T09:53:47 ICT" duration-ms="99" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testSuccessfulLoginAsStaff status=FAILURE method=LoginTest.testSuccessfulLoginAsStaff()[pri:0, instance:tests.LoginTest@4201a617] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureScreenshot -->
        <test-method is-config="true" signature="setUpTest()[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:47 ICT" name="setUpTest" finished-at="2025-07-25T09:53:47 ICT" duration-ms="287" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method signature="testValidationMissingPassword()[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:47 ICT" name="testValidationMissingPassword" description="TC05 - Validation missing Password" finished-at="2025-07-25T09:53:48 ICT" duration-ms="371" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidationMissingPassword -->
        <test-method is-config="true" signature="captureScreenshot(org.testng.ITestResult)[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:47 ICT" name="captureScreenshot" finished-at="2025-07-25T09:53:48 ICT" duration-ms="105" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testValidationMissingAccount status=SUCCESS method=LoginTest.testValidationMissingAccount()[pri:0, instance:tests.LoginTest@4201a617] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureScreenshot -->
        <test-method is-config="true" signature="captureScreenshot(org.testng.ITestResult)[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:48 ICT" name="captureScreenshot" finished-at="2025-07-25T09:53:48 ICT" duration-ms="104" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testValidationMissingPassword status=SUCCESS method=LoginTest.testValidationMissingPassword()[pri:0, instance:tests.LoginTest@4201a617] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureScreenshot -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.LoginTest@4201a617]" started-at="2025-07-25T09:53:48 ICT" name="tearDown" finished-at="2025-07-25T09:53:48 ICT" duration-ms="135" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.LoginTest -->
    </test> <!-- Login Test -->
  </suite> <!-- UI Automation Suite -->
</testng-results>
